tunnels:
  experiment:
    proto: tcp
    addr: 22
    metadata: "hello there"
  demo:
    proto: http
    addr: 9090
    hostname: demo.inconshreveable.com
    inspect: false
    auth: "demo:secret"
